import { describe, expect, it, vi } from "vitest";
import { createTenantContext, createTenantId } from "../domain/tenant-context";
import { withPrismaTenantContext, type PrismaTenantTransactionClient } from "./prisma-tenant-context";
function tenantContext(value: string) { const id=createTenantId(value); if(!id.ok) throw new Error(id.error.message); const context=createTenantContext({tenantId:id.value}); if(!context.ok) throw new Error(context.error.message); return context.value; }
function mockTx(){ return { $executeRawUnsafe:vi.fn().mockResolvedValue(1), tenantMembership:{findUnique:vi.fn()} } satisfies PrismaTenantTransactionClient; }
describe("withPrismaTenantContext",()=>{
 it("sets context before operation",async()=>{ const tx=mockTx(); const order:string[]=[]; tx.$executeRawUnsafe.mockImplementation(async()=>{order.push("context");return 1;}); const prisma={$transaction:vi.fn(async(operation:(tx:typeof tx)=>Promise<string>)=>{order.push("transaction");return operation(tx);})}; await withPrismaTenantContext(prisma,tenantContext("tenant-a"),async()=>{order.push("operation");return "ok";}); expect(order).toEqual(["transaction","context","operation"]); expect(tx.$executeRawUnsafe).toHaveBeenCalledWith("SELECT set_config('app.tenant_id', $1, true)","tenant-a");});
 it("propagates operation failures",async()=>{const tx=mockTx(); const failure=new Error("query failed"); const prisma={$transaction:vi.fn(async(operation:(tx:typeof tx)=>Promise<never>)=>operation(tx))}; await expect(withPrismaTenantContext(prisma,tenantContext("tenant-a"),async()=>{throw failure;})).rejects.toBe(failure);});
 it("does not execute operation when context setup fails",async()=>{const tx=mockTx(); const failure=new Error("context failed"); tx.$executeRawUnsafe.mockRejectedValue(failure); const operation=vi.fn(); const prisma={$transaction:vi.fn(async(callback:(tx:typeof tx)=>Promise<unknown>)=>callback(tx))}; await expect(withPrismaTenantContext(prisma,tenantContext("tenant-a"),operation)).rejects.toBe(failure); expect(operation).not.toHaveBeenCalled();});
});
